version: '3.8'

services:
  my-java-app:
    container_name: my-java-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms2g -Xmx2g  # Increase heap size (example: 2GB)
    ports:
      - "9200:9200"