name: Deploy to Local Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # This ensures it runs on your self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my-java-app .

      - name: Stop and Remove Existing Container
        run: |
          docker stop my-java-app || true  # Ignore if it doesn't exist
          docker rm my-java-app || true

      - name: Run Docker container
        run: docker run -d --name my-java-app -p 8080:8080 my-java-app
