name: Deploy to Local Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'

      - name: Build JAR with Maven
        run: mvn clean package

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker image
        run: docker-compose build

      - name: Save Docker image as a tar file
        run: docker save my-java-app -o my-java-app.tar

      - name: Copy Docker image to server
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: ./my-java-app.tar
          target: ~/my-java-app.tar

      - name: Deploy Docker image and restart container on server
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker load -i ~/my-java-app.tar
            cd /path/to/docker-compose # Change to the directory where your docker-compose.yml file is located
            docker-compose down
            docker-compose up -d
